version: "3.9"

networks:
  gift.net:
    driver: bridge

services:
  sql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      gift.net:
          aliases:
            - sql.db
            - sql326.net

  adminer:
    image: adminer
    # command: php -S 0.0.0.0:8080
    ports:
      # - "11555:8080"
      - "5080:8080"
    networks:
      - gift.net
  
  php:
    image: canals/php:latest
    ports:
      # - "11554:80"
      - "5180:80"
    volumes :
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./shared/img:/var/www/html/img
      - ./shared/css:/var/www/html/css
    working_dir: /var/www/html
    networks:
      - gift.net
    depends_on:
      - sql

  api:
    image: canals/php:latest
    ports:
      - "5280:80"
    volumes :
      - ./api/public:/var/www/html
      - ./api/src:/var/www/src
      - ./api/shared/img:/var/www/html/img
      - ./api/shared/css:/var/www/html/css
    working_dir: /var/www/html
    networks:
      - gift.net
    depends_on:
      - sql